<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Year</name>
   <tag></tag>
   <elementGuidId>521d317e-48bc-4bad-9148-9c6c0257f3b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-«r3»']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mb-2.flex.items-center.gap-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;Year:&quot;i >> nth=4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8c6ecce7-287f-4ca6-b176-39638629237b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2 flex items-center gap-2</value>
      <webElementGuid>5184c00e-3b5f-4aeb-87b3-b06f8ac42fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Year:</value>
      <webElementGuid>656dcb7c-5170-488a-8807-e275c4098297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-«r3»&quot;)/div[@class=&quot;p-3&quot;]/div[@class=&quot;flex flex-col px-4 py-2&quot;]/div[@class=&quot;mb-2 flex items-center gap-2&quot;]</value>
      <webElementGuid>61813c0c-dcf7-4e24-9eb3-3e18bf7d6862</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-«r3»']/div/div/div</value>
      <webElementGuid>b8b807f9-d59c-468a-b132-59c5f02a4569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::div[6]</value>
      <webElementGuid>bb02399d-0a73-4cda-afbc-1f800798450b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[1]/following::div[7]</value>
      <webElementGuid>673be91a-b957-421e-b968-f2553388fe60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous month'])[1]/preceding::div[1]</value>
      <webElementGuid>b295b483-36f0-4b76-b676-e2e60c580d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>29a2364a-5150-4576-95ba-6a5fc29e8ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Year:' or . = 'Year:')]</value>
      <webElementGuid>22cafada-dc22-4296-aed2-4e251de808bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
