<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_We Need Your FeedbackHello from Group 5_f7e772</name>
   <tag></tag>
   <elementGuidId>5a933ee1-63b8-4b12-9c49-d6bdabffcc62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-«r0»']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radix-«r0»</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;We Need Your Feedback!&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>405508bc-f16f-4409-92ce-5e18059b36d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>12c73005-92ce-48ce-9e9d-7f38a65e937b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-«r0»</value>
      <webElementGuid>826ab283-cb80-4443-96e2-554b1d8384aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>radix-«r2»</value>
      <webElementGuid>614b393a-d4b3-4c04-aba0-0da3cdc7280a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>radix-«r1»</value>
      <webElementGuid>d19428b8-c88a-4381-b621-5ed2d0c89055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>1616ba1b-2a44-492e-a9a7-7002d14e35c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>dialog-content</value>
      <webElementGuid>7b24806a-d370-43d8-84e3-f3613a8661f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-background data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 fixed top-[50%] left-[50%] z-50 grid w-full max-w-[calc(100%-2rem)] translate-x-[-50%] translate-y-[-50%] gap-4 rounded-lg border p-6 shadow-lg duration-200 sm:max-w-md</value>
      <webElementGuid>f8a3aea2-ad17-4609-8070-3f9272b353f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>367c91d5-5396-400c-9ff9-222fafe15909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We Need Your Feedback!Hello from Group 5 at RMIT University in Hanoi Campus!We're working on our Fullstack Web Development course project and would greatly appreciate your feedback on our website.Please take some time to explore all the features of our website, and when you're ready, visit our Feedback page to share your thoughts.Your feedback is invaluable to us and will help us improve our project. Thank you for your support!Explore FirstGo to Feedback PageClose</value>
      <webElementGuid>fbe32d38-03c4-4011-b2a3-cc4a0fd8226a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-«r0»&quot;)</value>
      <webElementGuid>047f7e4f-5d56-4107-9933-30bb4494f591</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='radix-«r0»']</value>
      <webElementGuid>45a25997-b73b-49a9-b1b8-5cd618545839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::div[3]</value>
      <webElementGuid>ac8d1fd7-599d-4fa0-9e3f-3364ce08c386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>293ad566-5ffb-4294-9fde-798775205b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'radix-«r0»' and (text() = concat(&quot;We Need Your Feedback!Hello from Group 5 at RMIT University in Hanoi Campus!We&quot; , &quot;'&quot; , &quot;re working on our Fullstack Web Development course project and would greatly appreciate your feedback on our website.Please take some time to explore all the features of our website, and when you&quot; , &quot;'&quot; , &quot;re ready, visit our Feedback page to share your thoughts.Your feedback is invaluable to us and will help us improve our project. Thank you for your support!Explore FirstGo to Feedback PageClose&quot;) or . = concat(&quot;We Need Your Feedback!Hello from Group 5 at RMIT University in Hanoi Campus!We&quot; , &quot;'&quot; , &quot;re working on our Fullstack Web Development course project and would greatly appreciate your feedback on our website.Please take some time to explore all the features of our website, and when you&quot; , &quot;'&quot; , &quot;re ready, visit our Feedback page to share your thoughts.Your feedback is invaluable to us and will help us improve our project. Thank you for your support!Explore FirstGo to Feedback PageClose&quot;))]</value>
      <webElementGuid>9bbeda52-0a44-4364-9b2a-b1bef6a636b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
