<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_We Need Your Feedback</name>
   <tag></tag>
   <elementGuidId>c7291402-8f76-4cd0-bc58-b20fefee41ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='radix-«r1»']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radix-«r1»</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;We Need Your Feedback!&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>9c57b72f-1950-448e-9c04-8f82f52fa344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-«r1»</value>
      <webElementGuid>d3ff980a-de90-4a3b-8071-0865e3e7b62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>dialog-title</value>
      <webElementGuid>74a49ca7-c2d5-42eb-824f-5e846dfd20e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-semibold flex items-center gap-2 text-xl</value>
      <webElementGuid>f17b5f42-0484-441a-9ae5-3a6acc003f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We Need Your Feedback!</value>
      <webElementGuid>1171d674-0855-4cf3-916c-3b146525b0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-«r1»&quot;)</value>
      <webElementGuid>eb857da0-be1a-40b1-a40b-95cbde4bf5ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='radix-«r1»']</value>
      <webElementGuid>d96bc6b6-c50e-4f44-a843-5c9cd4c09cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-«r0»']/div/h2</value>
      <webElementGuid>82556a94-8579-4d53-b362-4b266f914b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::h2[1]</value>
      <webElementGuid>1305c262-b16f-49ba-8c8f-82f7ab8bccb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore First'])[1]/preceding::h2[1]</value>
      <webElementGuid>08c2d04b-a05f-4d47-8b55-f9a3f968e636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to Feedback Page'])[1]/preceding::h2[1]</value>
      <webElementGuid>eb1771a7-4e37-41a9-87c2-ab6734e2d571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='We Need Your Feedback!']/parent::*</value>
      <webElementGuid>62f60cb2-56aa-4efa-8c6a-db8a5b81cfb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/h2</value>
      <webElementGuid>214a6600-714c-4ab2-820b-9c2d2c192532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'radix-«r1»' and (text() = 'We Need Your Feedback!' or . = 'We Need Your Feedback!')]</value>
      <webElementGuid>7a62257f-19f1-409a-a5a0-e4abb35c4f1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
