<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Password must be at least 6 characters</name>
   <tag></tag>
   <elementGuidId>bcabd874-d7d9-49f0-abdb-99aab8ec8991</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/section/ol/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ol > li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Notifications alt+T&quot;i >> internal:role=listitem >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ad62c588-1f8d-44f8-933c-cdd2f7a9c859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9803e299-ab0f-4579-838f-7bbba38ce020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rich-colors</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>00ca4137-1d1f-44a0-ae8e-74ac625e8b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-styled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>deac16b9-fa25-490d-819e-5e8d43f01342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mounted</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9a2025d7-4328-4bfc-9d62-ba14d2e69f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-promise</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6a2d1f35-1b6f-445f-a135-efbf8883b7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-swiped</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d665543-e1c0-49d7-ab60-aa1f93b13a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-removed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3c06a9c6-37ad-411b-b082-96c12b73736c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-visible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>34b525d0-237a-4dd3-bb9e-a2a8e8e15ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-y-position</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>a116bf19-cc3f-4718-852e-cf7668fcb4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-x-position</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>0cbb772d-bbbd-4591-94e5-a2f8a0ac00f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4f951339-2228-4cbd-a368-4905a12c16bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-front</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>64cbccba-4ed6-4ff6-a68e-65576ec56165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-swiping</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f83ebb89-f8b9-42d3-b6ca-1111228e371d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismissible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>152db1af-ac35-4c06-9e8a-dd4f9b372742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>a7330b42-dc94-46cb-8c90-548dd8ef3a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-swipe-out</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>344333a3-fade-4ae5-a45b-36d86f8616ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>41d2c971-561d-4a51-b815-60fa05cba7b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password must be at least 6 characters</value>
      <webElementGuid>f9aa3ad8-4ae6-4000-b37c-5300db4a4c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/section[1]/ol[1]/li[1]</value>
      <webElementGuid>4df30539-4a33-47cd-8223-b7d0b2eaba3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/ol/li</value>
      <webElementGuid>dd05fe62-d7cc-4752-a073-c0badb240e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::li[1]</value>
      <webElementGuid>dae468be-6e53-4769-b5e1-69cc5a705ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[1]/following::li[1]</value>
      <webElementGuid>f4c37f2c-9b0a-4cc5-939f-8da77ad5e249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password must be at least 6 characters'])[3]/preceding::li[1]</value>
      <webElementGuid>26f655f2-1514-4e48-bec3-aae557084f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li</value>
      <webElementGuid>2a8c4205-a5d6-4cc6-88af-519a78d553a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Password must be at least 6 characters' or . = 'Password must be at least 6 characters')]</value>
      <webElementGuid>e705af5a-1ff3-4dcf-b928-3a10d5c326ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
